MMS:
  email: 233
  password: 233
  savefolder_path: 233

RSS:
  url: 233
  key: 233333

Email:
  enable_email_notify: 1
  sender: 233
  receivers: 233
  smtp_host: 233
  smtp_port: 233
  mail_license: 114514
  send_logs: 1

  use_oauth2_outlook: 0
  outlook_client_id: 11451419-1981-0114-5141-919810114514
  outlook_client_secret: 114514191981011451419198101145141919810hengaaaa
  outlook_redirect_uri: http://localhost:9001

onedrive:
  enable_od_upload: 0
  od_client_id: 114514
  od_client_secret: 114514
  od_redirect_uri: 114514
  od_upload_dir: abcd # relative to rootï¼Œ do not use '/' at the beginning
